task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-11-3-snap
      image_family: freebsd-12-1-snap
      image_family: freebsd-13-0-snap

  install_script:
    - pkg update -f
    - pkg install -y cmake ninja pkgconf gettext nasm ncurses libcpuid pciutils libstatgrab

  build_script:
    - cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GTK=0
    - cmake --build build
    - cmake --install build

  run_script:
    - sudo CPUX_BCLK=100 cpu-x --issue-fmt
    - cat /tmp/cpu-x.log
    - cat /tmp/cpu-x-daemon.log
